version: '3'
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq-srv
    environment:
      - RABBITMQ_DEFAULT_USER=2workroom3 #用户名;
      - RABBITMQ_DEFAULT_PASS=1357924680_ #用户密码;
    restart: always
    ports:
      - "15672:15672" #15672为rabbitmq的web管理界面端口;
      - "5672:5672" #rabbitmq的服务端口;
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
